### ISSUE TITLE
CoreModule Question

### ISSUE THREAD

**Issue by demonGeek** [mathisGarberg/angular-folder-structure#105]
I have a (hopefully) simple question.

Reading ITNext article, I see the following:

> The CoreModule should contain singleton services (which is usually the case), universal components and other features where there’s only once instance per application.

When I look at the sample project, ```core.module.ts``` does not contain ```auth.service.ts``` or ```theme.service.ts``` and I was wondering why?

**Comment by TomHAnderson** [comment]
Services do not need to be declared.

**Comment by docwhite** [comment]
They are indeed singletons because they are [provided in root](https://angular.io/guide/singleton-services#using-providedin).

If they were not provided in root, then you would have to put them into the providers array of the providing module.

... I think (I'm still surfing my Angular learning curve).

Read: https://angular.io/guide/singleton-services

**Comment by TomHAnderson** [comment]
Adding my 2c here, the article referenced was the catalyst for this repository but this repository is not based on that article.
