### ISSUE TITLE
Import Services from Core module ?

### ISSUE THREAD

**Issue by patriceo** [mathisGarberg/angular-folder-structure#9]
Hello, thanks for this great repo and comments, this is always a big issue to tackle when creating an angular application from scratch and trying to find the most appropriated project structure. 

I like this template, however there is one thing that is confusing me.

You defined a Login module which only has a dependency on the SharedModule. So far so good, but the login page inside the Login module is importing a service from the Core module. Login modules does not have a dependency on the Core module  (this would create a dependency cycle). Correct me if I'm wrong but you are using a path alias "@app".

`import { AuthService } from '@app/core';`

Can we assume this is "good enough" because Core module always gets loaded ? Should we move this service to the SharedModule ? If not how should we decide whether a service should be in the core or the shared module if it has basically no dependencies ?

Feedbacks would be much appreciated ! Thanks !

**Comment by mathisGarberg** [comment]
Hi, @patriceo!

Great to hear the repo helps you out!

The `AuthModule` is an eagerly-loaded module, since it's imported in the `AppModule`. which means it has dependency to the rest of the application. This really means we don't need to import the SharedModule in the AuthModule, but as far as services goes, even lazy-loaded modules have access to them, and here's why: Angular creates a single, shared instance of the service through it's DI system. These singleton services are accessible from the root the application, which means any module have access to them. This is because services are app-scoped. You want to add the application-wide services in the core module to make them available everywhere.

There are however use-cases for services inside the `SharedModule`.

The `SharedModule` is the perfect place to declare reusable components. There is however a problem when we're dealing with services inside those components. Angular creates their own local instance of service inside every lazy-loaded module, which basically means we don't have access to the `CoreModule'` services in the `SharedModule'` components. This will probably result in a circular dependency error. But we need access to services inside the shared components as well. Luckily, Angular has an awesome feature called `ModuleWithProviders`. By importing the `SharedModule` in the `AppModule` and running the `forRoot()` method, every other component lazy-loaded or not, will have the same access to those services as well.

Best,
Mathis
